### ISSUE TITLE
Do Catalan and Basque datasets come from OpeNER or MultiBooked?

### ISSUE THREAD

**Issue by yslin1995** [jbarnesspain/blse#1]
Hey, there!

I found the paper writes 'We use the OpeNER English and Spanish datasets and the **MultiBooked Catalan and Basque datasets**.'. However in your code, datasets of these two low-resource languages also come from OpeNER(under the directory of opener_sents).

May I ask is it just a typo or you adjusted the resource?

**Comment by jerbarnes** [comment]
Hi,

The Catalan and Basque data are from the MultiBooked datasets. Putting them all under the same name was just for convenience. Sorry if that caused confusion.

**Comment by yslin1995** [comment]
Thanks a lot for your response, copy that.
