### ISSUE TITLE
Some questions about evaluate

### ISSUE THREAD

**Issue by MaCYbupt** [jbarnesspain/blse#2]
In file parameter_search, there are two kinds of evaluate function: multi-class classification and binary classification, and distinguished by parameter average, right? Why there is no "average" parameter in function evaluate?
Besides, in function evaluate, recall and f1 refer to the same, why?

**Comment by jerbarnes** [comment]
Hi,

The "average" parameter was from an older implementation and was later removed, but I forgot to take it out of parameter_search.py. Thanks for catching the mistake in evaluate. Recall and f1 were correctly reported in the paper, but this bug appeared when we were preparing the code after publishing. Both of these issues have been fixed. Thanks for pointing them out.
