### ISSUE TITLE
An error when run blse.py

### ISSUE THREAD

**Issue by superlyc** [jbarnesspain/blse#4]
Hi,
I was trying to run your code but this error 

"only one element tensors can be converted to Python scalars" for line 212 in blse.py.

New to pytorch. But it seems not converting a tensor to numpy array.

I am using the last version of torch.

Thanks

**Comment by JJplane** [comment]
> Hi,
> I was trying to run your code but this error
> 
> "only one element tensors can be converted to Python scalars" for line 212 in blse.py.
> 
> New to pytorch. But it seems not converting a tensor to numpy array.
> 
> I am using the last version of torch.
> 
> Thanks

you can try pytorch 0.2.0
