### ISSUE TITLE
Annotated data in the target language required

### ISSUE THREAD

**Issue by RacheleSprugnoli** [jbarnesspain/blse#5]
Hi!
I would like to use this code with English as source language and Latin as target language. In your paper it is written that "this model only requires a small bilingual lexicon, a source-language corpus annotated for sentiment, and monolingual word embeddings for each language." However, when I run the code, it requires the presence of dev, train and test sets also in the target language. Is there a way to avoid such requirement? If I had a lot of annotated data for Latin, I would try a supervised and monolingual approach :)
Thanks in advance!
Best wishes,
Rachele

**Comment by jerbarnes** [comment]
Hi Rachele,

Thanks for bringing up that point. I've made some changes to the blse.py
script to be able to train a model without providing any target dataset.
The only thing you have to do is give the argument --no_target_data True
when calling it from the command line:

>>> python3 blse.py -sv embeddings/blse/google.txt -tv
embeddings/blse/my_pretrained_latin_embeddings.txt --no_target_data True

I just pushed the changes, so you'll have to pull again.

I'm quite curious about what you're working on that involves Latin and
unsupervised sentiment analysis? I can only think of cool things!

Anyways, let me know if you run into any other problems with the code or
have any questions.

Best,
Jeremy

Hau idatzi du RacheleSprugnoli ***@***.***) erabiltzaileak
(2021 uzt. 12, al. (18:03)):

**Comment by RacheleSprugnoli** [comment]
Dear Jeremy,
thanks a lot for the kind and quick reply!
I work in an [ERC project](https://lila-erc.eu/) in which we create resources for Latin and make them interoperable using the Linked Data paradigm. We developed sentiment lexicons for Latin so to perform lexicon-based sentiment analysis, but we would like to experiment with other approaches such as the one you provide.
Thanks to the changes you made to the script, we were able to get a model. But now it is not clear to me how I can apply it to our Latin data. I'm sorry to bother you again but, could you please help me again?
Best wishes,
Rachele

**Comment by jerbarnes** [comment]
Hi again Rachele,

It sounds like a fun project! You're right that it was unclear how to use
the model for inference, so I've added a blse_inference.py script to the
github. You can use your trained model for inference in the following way:

python3 blse_inference.py --dataset my_inference_dataset.txt --savedir
my_models_dir  --src_vecs my_source_vecs.txt  --targ_vecs
my_target_vecs.txt  --outfile preds.txt

where my_inference_dataset.txt is just a .txt file with one pretokenized
sentence per line and my_models_dir is where you saved your trained models.
It will write the predictions to preds.txt, where each line will correspond
to the sentence in my_inference_dataset.txt.

I hope that helps and let me know if there's still anything that's not
clear!


Hau idatzi du RacheleSprugnoli ***@***.***) erabiltzaileak
(2021 uzt. 13, ar. (16:36)):

**Comment by RacheleSprugnoli** [comment]
Thanks a lot for your help!
Rachele
